#pragma once

#include <map>
#include <string>

#include "../pokemon/move/move.h"
#include "../pokemon/type/type.h"

using MoveDatabase = std::map<std::string, Move>;

// TODO: Add hidden power for all types
static const MoveDatabase move_database = {
    {"Pound", {"Pound", NORMAL, PHYSICAL, 40, 100, 35 } },
    {"Karate Chop", {"Karate Chop", FIGHTING, PHYSICAL, 50, 100, 25 } },
    {"Double Slap", {"Double Slap", NORMAL, PHYSICAL, 15, 85, 10 } },
    {"Comet Punch", {"Comet Punch", NORMAL, PHYSICAL, 18, 85, 15 } },
    {"Mega Punch", {"Mega Punch", NORMAL, PHYSICAL, 80, 85, 20 } },
    {"Pay Day", {"Pay Day", NORMAL, PHYSICAL, 40, 100, 20 } },
    {"Fire Punch", {"Fire Punch", FIRE, PHYSICAL, 75, 100, 15 } },
    {"Ice Punch", {"Ice Punch", ICE, PHYSICAL, 75, 100, 15 } },
    {"Thunder Punch", {"Thunder Punch", ELECTRIC, PHYSICAL, 75, 100, 15 } },
    {"Scratch", {"Scratch", NORMAL, PHYSICAL, 40, 100, 35 } },
    {"Vice Grip", {"Vice Grip", NORMAL, PHYSICAL, 55, 100, 30 } },
    {"Guillotine", {"Guillotine", NORMAL, PHYSICAL, -1, 30, 5 } },
    {"Razor Wind", {"Razor Wind", NORMAL, SPECIAL, 80, 100, 10 } },
    {"Swords Dance", {"Swords Dance", NORMAL, STATUS, -1, -1, 20 } },
    {"Cut", {"Cut", NORMAL, PHYSICAL, 50, 95, 30 } },
    {"Gust", {"Gust", FLYING, SPECIAL, 40, 100, 35 } },
    {"Wing Attack", {"Wing Attack", FLYING, PHYSICAL, 60, 100, 35 } },
    {"Whirlwind", {"Whirlwind", NORMAL, STATUS, -1, 100, 20 } },
    {"Fly", {"Fly", FLYING, PHYSICAL, 90, 95, 15 } },
    {"Bind", {"Bind", NORMAL, PHYSICAL, 15, 85, 20 } },
    {"Slam", {"Slam", NORMAL, PHYSICAL, 80, 75, 20 } },
    {"Vine Whip", {"Vine Whip", GRASS, PHYSICAL, 45, 100, 25 } },
    {"Stomp", {"Stomp", NORMAL, PHYSICAL, 65, 100, 20 } },
    {"Double Kick", {"Double Kick", FIGHTING, PHYSICAL, 30, 100, 30 } },
    {"Mega Kick", {"Mega Kick", NORMAL, PHYSICAL, 120, 75, 5 } },
    {"Jump Kick", {"Jump Kick", FIGHTING, PHYSICAL, 130, 95, 10 } },
    {"Rolling Kick", {"Rolling Kick", FIGHTING, PHYSICAL, 60, 85, 15 } },
    {"Sand Attack", {"Sand Attack", GROUND, STATUS, -1, 100, 15 } },
    {"Headbutt", {"Headbutt", NORMAL, PHYSICAL, 70, 100, 15 } },
    {"Horn Attack", {"Horn Attack", NORMAL, PHYSICAL, 65, 100, 25 } },
    {"Fury Attack", {"Fury Attack", NORMAL, PHYSICAL, 15, 85, 20 } },
    {"Horn Drill", {"Horn Drill", NORMAL, PHYSICAL, -1, 30, 5 } },
    {"Tackle", {"Tackle", NORMAL, PHYSICAL, 50, 100, 35 } },
    {"Body Slam", {"Body Slam", NORMAL, PHYSICAL, 85, 100, 15 } },
    {"Wrap", {"Wrap", NORMAL, PHYSICAL, 15, 90, 20 } },
    {"Take Down", {"Take Down", NORMAL, PHYSICAL, 90, 85, 20 } },
    {"Thrash", {"Thrash", NORMAL, PHYSICAL, 120, 100, 10 } },
    {"Double-Edge", {"Double-Edge", NORMAL, PHYSICAL, 120, 100, 15 } },
    {"Tail Whip", {"Tail Whip", NORMAL, STATUS, -1, 100, 30 } },
    {"Poison Sting", {"Poison Sting", POISON, PHYSICAL, 15, 100, 35 } },
    {"Twineedle", {"Twineedle", BUG, PHYSICAL, 25, 100, 20 } },
    {"Pin Missile", {"Pin Missile", BUG, PHYSICAL, 25, 95, 20 } },
    {"Leer", {"Leer", NORMAL, STATUS, -1, 100, 30 } },
    {"Bite", {"Bite", DARK, PHYSICAL, 60, 100, 25 } },
    {"Growl", {"Growl", NORMAL, STATUS, -1, 100, 40 } },
    {"Roar", {"Roar", NORMAL, STATUS, -1, -1, 20 } },
    {"Sing", {"Sing", NORMAL, STATUS, -1, 55, 15 } },
    {"Supersonic", {"Supersonic", NORMAL, STATUS, -1, 55, 20 } },
    {"Sonic Boom", {"Sonic Boom", NORMAL, SPECIAL, -1, 90, 20 } },
    {"Disable", {"Disable", NORMAL, STATUS, -1, 100, 20 } },
    {"Acid", {"Acid", POISON, SPECIAL, 40, 100, 30 } },
    {"Ember", {"Ember", FIRE, SPECIAL, 40, 100, 25 } },
    {"Flamethrower", {"Flamethrower", FIRE, SPECIAL, 90, 100, 15 } },
    {"Mist", {"Mist", ICE, STATUS, -1, -1, 30 } },
    {"Water Gun", {"Water Gun", WATER, SPECIAL, 40, 100, 25 } },
    {"Hydro Pump", {"Hydro Pump", WATER, SPECIAL, 110, 80, 5 } },
    {"Surf", {"Surf", WATER, SPECIAL, 90, 100, 15 } },
    {"Ice Beam", {"Ice Beam", ICE, SPECIAL, 90, 100, 10 } },
    {"Blizzard", {"Blizzard", ICE, SPECIAL, 110, 70, 5 } },
    {"Psybeam", {"Psybeam", PSYCHIC, SPECIAL, 65, 100, 20 } },
    {"Bubble Beam", {"Bubble Beam", WATER, SPECIAL, 65, 100, 20 } },
    {"Aurora Beam", {"Aurora Beam", ICE, SPECIAL, 65, 100, 20 } },
    {"Hyper Beam", {"Hyper Beam", NORMAL, SPECIAL, 150, 90, 5 } },
    {"Peck", {"Peck", FLYING, PHYSICAL, 35, 100, 35 } },
    {"Drill Peck", {"Drill Peck", FLYING, PHYSICAL, 80, 100, 20 } },
    {"Submission", {"Submission", FIGHTING, PHYSICAL, 80, 80, 25 } },
    {"Low Kick", {"Low Kick", FIGHTING, PHYSICAL, -1, 100, 20 } },
    {"Counter", {"Counter", FIGHTING, PHYSICAL, -1, 100, 20 } },
    {"Seismic Toss", {"Seismic Toss", FIGHTING, PHYSICAL, -1, 100, 20 } },
    {"Strength", {"Strength", NORMAL, PHYSICAL, 80, 100, 15 } },
    {"Absorb", {"Absorb", GRASS, SPECIAL, 20, 100, 25 } },
    {"Mega Drain", {"Mega Drain", GRASS, SPECIAL, 40, 100, 15 } },
    {"Leech Seed", {"Leech Seed", GRASS, STATUS, -1, 90, 10 } },
    {"Growth", {"Growth", NORMAL, STATUS, -1, -1, 40 } },
    {"Razor Leaf", {"Razor Leaf", GRASS, PHYSICAL, 55, 95, 25 } },
    {"Solar Beam", {"Solar Beam", GRASS, SPECIAL, 120, 100, 10 } },
    {"Poison Powder", {"Poison Powder", POISON, STATUS, -1, 75, 35 } },
    {"Stun Spore", {"Stun Spore", GRASS, STATUS, -1, 75, 30 } },
    {"Sleep Powder", {"Sleep Powder", GRASS, STATUS, -1, 75, 15 } },
    {"Petal Dance", {"Petal Dance", GRASS, SPECIAL, 120, 100, 10 } },
    {"String Shot", {"String Shot", BUG, STATUS, -1, 95, 40 } },
    {"Dragon Rage", {"Dragon Rage", DRAGON, SPECIAL, -1, 100, 10 } },
    {"Fire Spin", {"Fire Spin", FIRE, SPECIAL, 35, 85, 15 } },
    {"Thunder Shock", {"Thunder Shock", ELECTRIC, SPECIAL, 40, 100, 30 } },
    {"Thunderbolt", {"Thunderbolt", ELECTRIC, SPECIAL, 90, 100, 15 } },
    {"Thunder Wave", {"Thunder Wave", ELECTRIC, STATUS, -1, 100, 20 } },
    {"Thunder", {"Thunder", ELECTRIC, SPECIAL, 110, 70, 10 } },
    {"Rock Throw", {"Rock Throw", ROCK, PHYSICAL, 50, 90, 15 } },
    {"Earthquake", {"Earthquake", GROUND, PHYSICAL, 100, 100, 10 } },
    {"Fissure", {"Fissure", GROUND, PHYSICAL, -1, 30, 5 } },
    {"Dig", {"Dig", GROUND, PHYSICAL, 80, 100, 10 } },
    {"Toxic", {"Toxic", POISON, STATUS, -1, 90, 10 } },
    {"Confusion", {"Confusion", PSYCHIC, SPECIAL, 50, 100, 25 } },
    {"Psychic", {"Psychic", PSYCHIC, SPECIAL, 90, 100, 10 } },
    {"Hypnosis", {"Hypnosis", PSYCHIC, STATUS, -1, 60, 20 } },
    {"Meditate", {"Meditate", PSYCHIC, STATUS, -1, -1, 40 } },
    {"Agility", {"Agility", PSYCHIC, STATUS, -1, -1, 30 } },
    {"Quick Attack", {"Quick Attack", NORMAL, PHYSICAL, 40, 100, 30 } },
    {"Rage", {"Rage", NORMAL, PHYSICAL, 20, 100, 20 } },
    {"Teleport", {"Teleport", PSYCHIC, STATUS, -1, -1, 20 } },
    {"Night Shade", {"Night Shade", GHOST, SPECIAL, -1, 100, 15 } },
    {"Mimic", {"Mimic", NORMAL, STATUS, -1, -1, 10 } },
    {"Screech", {"Screech", NORMAL, STATUS, -1, 85, 40 } },
    {"Double Team", {"Double Team", NORMAL, STATUS, -1, -1, 15 } },
    {"Recover", {"Recover", NORMAL, STATUS, -1, -1, 10 } },
    {"Harden", {"Harden", NORMAL, STATUS, -1, -1, 30 } },
    {"Minimize", {"Minimize", NORMAL, STATUS, -1, -1, 10 } },
    {"Smokescreen", {"Smokescreen", NORMAL, STATUS, -1, 100, 20 } },
    {"Confuse Ray", {"Confuse Ray", GHOST, STATUS, -1, 100, 10 } },
    {"Withdraw", {"Withdraw", WATER, STATUS, -1, -1, 40 } },
    {"Defense Curl", {"Defense Curl", NORMAL, STATUS, -1, -1, 40 } },
    {"Barrier", {"Barrier", PSYCHIC, STATUS, -1, -1, 30 } },
    {"Light Screen", {"Light Screen", PSYCHIC, STATUS, -1, -1, 30 } },
    {"Haze", {"Haze", ICE, STATUS, -1, -1, 30 } },
    {"Reflect", {"Reflect", PSYCHIC, STATUS, -1, -1, 20 } },
    {"Focus Energy", {"Focus Energy", NORMAL, STATUS, -1, -1, 30 } },
    {"Bide", {"Bide", NORMAL, PHYSICAL, -1, -1, 10 } },
    {"Metronome", {"Metronome", NORMAL, STATUS, -1, -1, 10 } },
    {"Mirror Move", {"Mirror Move", FLYING, STATUS, -1, -1, 20 } },
    {"Self-Destruct", {"Self-Destruct", NORMAL, PHYSICAL, 200, 100, 5 } },
    {"Egg Bomb", {"Egg Bomb", NORMAL, PHYSICAL, 100, 75, 10 } },
    {"Lick", {"Lick", GHOST, PHYSICAL, 30, 100, 30 } },
    {"Smog", {"Smog", POISON, SPECIAL, 30, 70, 20 } },
    {"Sludge", {"Sludge", POISON, SPECIAL, 65, 100, 20 } },
    {"Bone Club", {"Bone Club", GROUND, PHYSICAL, 65, 85, 20 } },
    {"Fire Blast", {"Fire Blast", FIRE, SPECIAL, 110, 85, 5 } },
    {"Waterfall", {"Waterfall", WATER, PHYSICAL, 80, 100, 15 } },
    {"Clamp", {"Clamp", WATER, PHYSICAL, 35, 85, 10 } },
    {"Swift", {"Swift", NORMAL, SPECIAL, 60, -1, 20 } },
    {"Skull Bash", {"Skull Bash", NORMAL, PHYSICAL, 130, 100, 10 } },
    {"Spike Cannon", {"Spike Cannon", NORMAL, PHYSICAL, 20, 100, 15 } },
    {"Constrict", {"Constrict", NORMAL, PHYSICAL, 10, 100, 35 } },
    {"Amnesia", {"Amnesia", PSYCHIC, STATUS, -1, -1, 20 } },
    {"Kinesis", {"Kinesis", PSYCHIC, STATUS, -1, 80, 15 } },
    {"Soft-Boiled", {"Soft-Boiled", NORMAL, STATUS, -1, -1, 10 } },
    {"High Jump Kick", {"High Jump Kick", FIGHTING, PHYSICAL, 130, 90, 10 } },
    {"Glare", {"Glare", NORMAL, STATUS, -1, 100, 30 } },
    {"Dream Eater", {"Dream Eater", PSYCHIC, SPECIAL, 100, 100, 15 } },
    {"Poison Gas", {"Poison Gas", POISON, STATUS, -1, 90, 40 } },
    {"Barrage", {"Barrage", NORMAL, PHYSICAL, 15, 85, 20 } },
    {"Leech Life", {"Leech Life", BUG, PHYSICAL, 20, 100, 15 } },
    {"Lovely Kiss", {"Lovely Kiss", NORMAL, STATUS, -1, 75, 10 } },
    {"Sky Attack", {"Sky Attack", FLYING, PHYSICAL, 140, 90, 5 } },
    {"Transform", {"Transform", NORMAL, STATUS, -1, -1, 10 } },
    {"Bubble", {"Bubble", WATER, SPECIAL, 40, 100, 30 } },
    {"Dizzy Punch", {"Dizzy Punch", NORMAL, PHYSICAL, 70, 100, 10 } },
    {"Spore", {"Spore", GRASS, STATUS, -1, 100, 15 } },
    {"Flash", {"Flash", NORMAL, STATUS, -1, 100, 20 } },
    {"Psywave", {"Psywave", PSYCHIC, SPECIAL, -1, 100, 15 } },
    {"Splash", {"Splash", NORMAL, STATUS, -1, -1, 40 } },
    {"Acid Armor", {"Acid Armor", POISON, STATUS, -1, -1, 20 } },
    {"Crabhammer", {"Crabhammer", WATER, PHYSICAL, 100, 90, 10 } },
    {"Explosion", {"Explosion", NORMAL, PHYSICAL, 250, 100, 5 } },
    {"Fury Swipes", {"Fury Swipes", NORMAL, PHYSICAL, 18, 80, 15 } },
    {"Bonemerang", {"Bonemerang", GROUND, PHYSICAL, 50, 90, 10 } },
    {"Rest", {"Rest", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Rock Slide", {"Rock Slide", ROCK, PHYSICAL, 75, 90, 10 } },
    {"Hyper Fang", {"Hyper Fang", NORMAL, PHYSICAL, 80, 90, 15 } },
    {"Sharpen", {"Sharpen", NORMAL, STATUS, -1, -1, 30 } },
    {"Conversion", {"Conversion", NORMAL, STATUS, -1, -1, 30 } },
    {"Tri Attack", {"Tri Attack", NORMAL, SPECIAL, 80, 100, 10 } },
    {"Super Fang", {"Super Fang", NORMAL, PHYSICAL, -1, 90, 10 } },
    {"Slash", {"Slash", NORMAL, PHYSICAL, 70, 100, 20 } },
    {"Substitute", {"Substitute", NORMAL, STATUS, -1, -1, 10 } },
    {"Struggle", {"Struggle", NORMAL, PHYSICAL, 50, -1, -1 } },
    {"Sketch", {"Sketch", NORMAL, STATUS, -1, -1, 1 } },
    {"Triple Kick", {"Triple Kick", FIGHTING, PHYSICAL, 10, 90, 10 } },
    {"Thief", {"Thief", DARK, PHYSICAL, 60, 100, 10 } },
    {"Spider Web", {"Spider Web", BUG, STATUS, -1, -1, 10 } },
    {"Mind Reader", {"Mind Reader", NORMAL, STATUS, -1, -1, 5 } },
    {"Nightmare", {"Nightmare", GHOST, STATUS, -1, 100, 15 } },
    {"Flame Wheel", {"Flame Wheel", FIRE, PHYSICAL, 60, 100, 25 } },
    {"Snore", {"Snore", NORMAL, SPECIAL, 50, 100, 15 } },
    {"Curse", {"Curse", GHOST, STATUS, -1, -1, -1 } },
    {"Flail", {"Flail", NORMAL, PHYSICAL, -1, 100, 15 } },
    {"Conversion 2", {"Conversion 2", NORMAL, STATUS, -1, -1, 30 } },
    {"Aeroblast", {"Aeroblast", FLYING, SPECIAL, 100, 95, 5 } },
    {"Cotton Spore", {"Cotton Spore", GRASS, STATUS, -1, 100, 40 } },
    {"Reversal", {"Reversal", FIGHTING, PHYSICAL, -1, 100, 15 } },
    {"Spite", {"Spite", GHOST, STATUS, -1, 100, 10 } },
    {"Powder Snow", {"Powder Snow", ICE, SPECIAL, 40, 100, 25 } },
    {"Protect", {"Protect", NORMAL, STATUS, -1, -1, 10 } },
    {"Mach Punch", {"Mach Punch", FIGHTING, PHYSICAL, 40, 100, 30 } },
    {"Scary Face", {"Scary Face", NORMAL, STATUS, -1, 100, 10 } },
    {"Feint Attack", {"Feint Attack", DARK, PHYSICAL, 60, -1, 20 } },
    {"Sweet Kiss", {"Sweet Kiss", FAIRY, STATUS, -1, 75, 10 } },
    {"Belly Drum", {"Belly Drum", NORMAL, STATUS, -1, -1, 10 } },
    {"Sludge Bomb", {"Sludge Bomb", POISON, SPECIAL, 90, 100, 10 } },
    {"Mud-Slap", {"Mud-Slap", GROUND, SPECIAL, 20, 100, 10 } },
    {"Octazooka", {"Octazooka", WATER, SPECIAL, 65, 85, 10 } },
    {"Spikes", {"Spikes", GROUND, STATUS, -1, -1, 20 } },
    {"Zap Cannon", {"Zap Cannon", ELECTRIC, SPECIAL, 120, 50, 5 } },
    {"Foresight", {"Foresight", NORMAL, STATUS, -1, -1, 40 } },
    {"Destiny Bond", {"Destiny Bond", GHOST, STATUS, -1, -1, 5 } },
    {"Perish Song", {"Perish Song", NORMAL, STATUS, -1, -1, 5 } },
    {"Icy Wind", {"Icy Wind", ICE, SPECIAL, 55, 95, 15 } },
    {"Detect", {"Detect", FIGHTING, STATUS, -1, -1, 5 } },
    {"Bone Rush", {"Bone Rush", GROUND, PHYSICAL, 25, 80, 10 } },
    {"Lock-On", {"Lock-On", NORMAL, STATUS, -1, -1, 5 } },
    {"Outrage", {"Outrage", DRAGON, PHYSICAL, 120, 100, 15 } },
    {"Sandstorm", {"Sandstorm", ROCK, STATUS, -1, -1, 10 } },
    {"Giga Drain", {"Giga Drain", GRASS, SPECIAL, 75, 100, 10 } },
    {"Endure", {"Endure", NORMAL, STATUS, -1, -1, 10 } },
    {"Charm", {"Charm", FAIRY, STATUS, -1, 100, 20 } },
    {"Rollout", {"Rollout", ROCK, PHYSICAL, 30, 90, 20 } },
    {"False Swipe", {"False Swipe", NORMAL, PHYSICAL, 40, 100, 40 } },
    {"Swagger", {"Swagger", NORMAL, STATUS, -1, 90, 15 } },
    {"Milk Drink", {"Milk Drink", NORMAL, STATUS, -1, -1, 10 } },
    {"Spark", {"Spark", ELECTRIC, PHYSICAL, 65, 100, 20 } },
    {"Fury Cutter", {"Fury Cutter", BUG, PHYSICAL, 40, 95, 20 } },
    {"Steel Wing", {"Steel Wing", STEEL, PHYSICAL, 70, 90, 25 } },
    {"Mean Look", {"Mean Look", NORMAL, STATUS, -1, -1, 5 } },
    {"Attract", {"Attract", NORMAL, STATUS, -1, 100, 15 } },
    {"Sleep Talk", {"Sleep Talk", NORMAL, STATUS, -1, -1, 10 } },
    {"Heal Bell", {"Heal Bell", NORMAL, STATUS, -1, -1, 5 } },
    {"Return", {"Return", NORMAL, PHYSICAL, -1, 100, 20 } },
    {"Present", {"Present", NORMAL, PHYSICAL, -1, 90, 15 } },
    {"Frustration", {"Frustration", NORMAL, PHYSICAL, -1, 100, 20 } },
    {"Safeguard", {"Safeguard", NORMAL, STATUS, -1, -1, 25 } },
    {"Pain Split", {"Pain Split", NORMAL, STATUS, -1, -1, 20 } },
    {"Sacred Fire", {"Sacred Fire", FIRE, PHYSICAL, 100, 95, 5 } },
    {"Magnitude", {"Magnitude", GROUND, PHYSICAL, -1, 100, 30 } },
    {"Dynamic Punch", {"Dynamic Punch", FIGHTING, PHYSICAL, 100, 50, 5 } },
    {"Megahorn", {"Megahorn", BUG, PHYSICAL, 120, 85, 10 } },
    {"Dragon Breath", {"Dragon Breath", DRAGON, SPECIAL, 60, 100, 20 } },
    {"Baton Pass", {"Baton Pass", NORMAL, STATUS, -1, -1, 40 } },
    {"Encore", {"Encore", NORMAL, STATUS, -1, 100, 5 } },
    {"Pursuit", {"Pursuit", DARK, PHYSICAL, 40, 100, 20 } },
    {"Rapid Spin", {"Rapid Spin", NORMAL, PHYSICAL, 20, 100, 40 } },
    {"Sweet Scent", {"Sweet Scent", NORMAL, STATUS, -1, 100, 20 } },
    {"Iron Tail", {"Iron Tail", STEEL, PHYSICAL, 100, 75, 15 } },
    {"Metal Claw", {"Metal Claw", STEEL, PHYSICAL, 50, 95, 35 } },
    {"Vital Throw", {"Vital Throw", FIGHTING, PHYSICAL, 70, -1, 10 } },
    {"Morning Sun", {"Morning Sun", NORMAL, STATUS, -1, -1, 5 } },
    {"Synthesis", {"Synthesis", GRASS, STATUS, -1, -1, 5 } },
    {"Moonlight", {"Moonlight", FAIRY, STATUS, -1, -1, 5 } },
    {"Hidden Power", {"Hidden Power", NORMAL, SPECIAL, 60, 100, 15 } },
    {"Cross Chop", {"Cross Chop", FIGHTING, PHYSICAL, 100, 80, 5 } },
    {"Twister", {"Twister", DRAGON, SPECIAL, 40, 100, 20 } },
    {"Rain Dance", {"Rain Dance", WATER, STATUS, -1, -1, 5 } },
    {"Sunny Day", {"Sunny Day", FIRE, STATUS, -1, -1, 5 } },
    {"Crunch", {"Crunch", DARK, PHYSICAL, 80, 100, 15 } },
    {"Mirror Coat", {"Mirror Coat", PSYCHIC, SPECIAL, -1, 100, 20 } },
    {"Psych Up", {"Psych Up", NORMAL, STATUS, -1, -1, 10 } },
    {"Extreme Speed", {"Extreme Speed", NORMAL, PHYSICAL, 80, 100, 5 } },
    {"Ancient Power", {"Ancient Power", ROCK, SPECIAL, 60, 100, 5 } },
    {"Shadow Ball", {"Shadow Ball", GHOST, SPECIAL, 80, 100, 15 } },
    {"Future Sight", {"Future Sight", PSYCHIC, SPECIAL, 120, 100, 10 } },
    {"Rock Smash", {"Rock Smash", FIGHTING, PHYSICAL, 40, 100, 15 } },
    {"Whirlpool", {"Whirlpool", WATER, SPECIAL, 35, 85, 15 } },
    {"Beat Up", {"Beat Up", DARK, PHYSICAL, -1, 100, 10 } },
    {"Fake Out", {"Fake Out", NORMAL, PHYSICAL, 40, 100, 10 } },
    {"Uproar", {"Uproar", NORMAL, SPECIAL, 90, 100, 10 } },
    {"Stockpile", {"Stockpile", NORMAL, STATUS, -1, -1, 20 } },
    {"Spit Up", {"Spit Up", NORMAL, SPECIAL, -1, 100, 10 } },
    {"Swallow", {"Swallow", NORMAL, STATUS, -1, -1, 10 } },
    {"Heat Wave", {"Heat Wave", FIRE, SPECIAL, 95, 90, 10 } },
    {"Hail", {"Hail", ICE, STATUS, -1, -1, 10 } },
    {"Torment", {"Torment", DARK, STATUS, -1, 100, 15 } },
    {"Flatter", {"Flatter", DARK, STATUS, -1, 100, 15 } },
    {"Will-O-Wisp", {"Will-O-Wisp", FIRE, STATUS, -1, 85, 15 } },
    {"Memento", {"Memento", DARK, STATUS, -1, 100, 10 } },
    {"Facade", {"Facade", NORMAL, PHYSICAL, 70, 100, 20 } },
    {"Focus Punch", {"Focus Punch", FIGHTING, PHYSICAL, 150, 100, 20 } },
    {"Smelling Salts", {"Smelling Salts", NORMAL, PHYSICAL, 70, 100, 10 } },
    {"Follow Me", {"Follow Me", NORMAL, STATUS, -1, -1, 20 } },
    {"Nature Power", {"Nature Power", NORMAL, STATUS, -1, -1, 20 } },
    {"Charge", {"Charge", ELECTRIC, STATUS, -1, -1, 20 } },
    {"Taunt", {"Taunt", DARK, STATUS, -1, 100, 20 } },
    {"Helping Hand", {"Helping Hand", NORMAL, STATUS, -1, -1, 20 } },
    {"Trick", {"Trick", PSYCHIC, STATUS, -1, 100, 10 } },
    {"Role Play", {"Role Play", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Wish", {"Wish", NORMAL, STATUS, -1, -1, 10 } },
    {"Assist", {"Assist", NORMAL, STATUS, -1, -1, 20 } },
    {"Ingrain", {"Ingrain", GRASS, STATUS, -1, -1, 20 } },
    {"Superpower", {"Superpower", FIGHTING, PHYSICAL, 120, 100, 5 } },
    {"Magic Coat", {"Magic Coat", PSYCHIC, STATUS, -1, -1, 15 } },
    {"Recycle", {"Recycle", NORMAL, STATUS, -1, -1, 10 } },
    {"Revenge", {"Revenge", FIGHTING, PHYSICAL, 60, 100, 10 } },
    {"Brick Break", {"Brick Break", FIGHTING, PHYSICAL, 75, 100, 15 } },
    {"Yawn", {"Yawn", NORMAL, STATUS, -1, -1, 10 } },
    {"Knock Off", {"Knock Off", DARK, PHYSICAL, 65, 100, 20 } },
    {"Endeavor", {"Endeavor", NORMAL, PHYSICAL, -1, 100, 5 } },
    {"Eruption", {"Eruption", FIRE, SPECIAL, 150, 100, 5 } },
    {"Skill Swap", {"Skill Swap", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Imprison", {"Imprison", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Refresh", {"Refresh", NORMAL, STATUS, -1, -1, 20 } },
    {"Grudge", {"Grudge", GHOST, STATUS, -1, -1, 5 } },
    {"Snatch", {"Snatch", DARK, STATUS, -1, -1, 10 } },
    {"Secret Power", {"Secret Power", NORMAL, PHYSICAL, 70, 100, 20 } },
    {"Dive", {"Dive", WATER, PHYSICAL, 80, 100, 10 } },
    {"Arm Thrust", {"Arm Thrust", FIGHTING, PHYSICAL, 15, 100, 20 } },
    {"Camouflage", {"Camouflage", NORMAL, STATUS, -1, -1, 20 } },
    {"Tail Glow", {"Tail Glow", BUG, STATUS, -1, -1, 20 } },
    {"Luster Purge", {"Luster Purge", PSYCHIC, SPECIAL, 70, 100, 5 } },
    {"Mist Ball", {"Mist Ball", PSYCHIC, SPECIAL, 70, 100, 5 } },
    {"Feather Dance", {"Feather Dance", FLYING, STATUS, -1, 100, 15 } },
    {"Teeter Dance", {"Teeter Dance", NORMAL, STATUS, -1, 100, 20 } },
    {"Blaze Kick", {"Blaze Kick", FIRE, PHYSICAL, 85, 90, 10 } },
    {"Mud Sport", {"Mud Sport", GROUND, STATUS, -1, -1, 15 } },
    {"Ice Ball", {"Ice Ball", ICE, PHYSICAL, 30, 90, 20 } },
    {"Needle Arm", {"Needle Arm", GRASS, PHYSICAL, 60, 100, 15 } },
    {"Slack Off", {"Slack Off", NORMAL, STATUS, -1, -1, 10 } },
    {"Hyper Voice", {"Hyper Voice", NORMAL, SPECIAL, 90, 100, 10 } },
    {"Poison Fang", {"Poison Fang", POISON, PHYSICAL, 50, 100, 15 } },
    {"Crush Claw", {"Crush Claw", NORMAL, PHYSICAL, 75, 95, 10 } },
    {"Blast Burn", {"Blast Burn", FIRE, SPECIAL, 150, 90, 5 } },
    {"Hydro Cannon", {"Hydro Cannon", WATER, SPECIAL, 150, 90, 5 } },
    {"Meteor Mash", {"Meteor Mash", STEEL, PHYSICAL, 90, 90, 10 } },
    {"Astonish", {"Astonish", GHOST, PHYSICAL, 30, 100, 15 } },
    {"Weather Ball", {"Weather Ball", NORMAL, SPECIAL, 50, 100, 10 } },
    {"Aromatherapy", {"Aromatherapy", GRASS, STATUS, -1, -1, 5 } },
    {"Fake Tears", {"Fake Tears", DARK, STATUS, -1, 100, 20 } },
    {"Air Cutter", {"Air Cutter", FLYING, SPECIAL, 60, 95, 25 } },
    {"Overheat", {"Overheat", FIRE, SPECIAL, 130, 90, 5 } },
    {"Odor Sleuth", {"Odor Sleuth", NORMAL, STATUS, -1, -1, 40 } },
    {"Rock Tomb", {"Rock Tomb", ROCK, PHYSICAL, 60, 95, 15 } },
    {"Silver Wind", {"Silver Wind", BUG, SPECIAL, 60, 100, 5 } },
    {"Metal Sound", {"Metal Sound", STEEL, STATUS, -1, 85, 40 } },
    {"Grass Whistle", {"Grass Whistle", GRASS, STATUS, -1, 55, 15 } },
    {"Tickle", {"Tickle", NORMAL, STATUS, -1, 100, 20 } },
    {"Cosmic Power", {"Cosmic Power", PSYCHIC, STATUS, -1, -1, 20 } },
    {"Water Spout", {"Water Spout", WATER, SPECIAL, 150, 100, 5 } },
    {"Signal Beam", {"Signal Beam", BUG, SPECIAL, 75, 100, 15 } },
    {"Shadow Punch", {"Shadow Punch", GHOST, PHYSICAL, 60, -1, 20 } },
    {"Extrasensory", {"Extrasensory", PSYCHIC, SPECIAL, 80, 100, 20 } },
    {"Sky Uppercut", {"Sky Uppercut", FIGHTING, PHYSICAL, 85, 90, 15 } },
    {"Sand Tomb", {"Sand Tomb", GROUND, PHYSICAL, 35, 85, 15 } },
    {"Sheer Cold", {"Sheer Cold", ICE, SPECIAL, -1, 30, 5 } },
    {"Muddy Water", {"Muddy Water", WATER, SPECIAL, 90, 85, 10 } },
    {"Bullet Seed", {"Bullet Seed", GRASS, PHYSICAL, 25, 100, 30 } },
    {"Aerial Ace", {"Aerial Ace", FLYING, PHYSICAL, 60, -1, 20 } },
    {"Icicle Spear", {"Icicle Spear", ICE, PHYSICAL, 25, 100, 30 } },
    {"Iron Defense", {"Iron Defense", STEEL, STATUS, -1, -1, 15 } },
    {"Block", {"Block", NORMAL, STATUS, -1, -1, 5 } },
    {"Howl", {"Howl", NORMAL, STATUS, -1, -1, 40 } },
    {"Dragon Claw", {"Dragon Claw", DRAGON, PHYSICAL, 80, 100, 15 } },
    {"Frenzy Plant", {"Frenzy Plant", GRASS, SPECIAL, 150, 90, 5 } },
    {"Bulk Up", {"Bulk Up", FIGHTING, STATUS, -1, -1, 20 } },
    {"Bounce", {"Bounce", FLYING, PHYSICAL, 85, 85, 5 } },
    {"Mud Shot", {"Mud Shot", GROUND, SPECIAL, 55, 95, 15 } },
    {"Poison Tail", {"Poison Tail", POISON, PHYSICAL, 50, 100, 25 } },
    {"Covet", {"Covet", NORMAL, PHYSICAL, 60, 100, 40 } },
    {"Volt Tackle", {"Volt Tackle", ELECTRIC, PHYSICAL, 120, 100, 15 } },
    {"Magical Leaf", {"Magical Leaf", GRASS, SPECIAL, 60, -1, 20 } },
    {"Water Sport", {"Water Sport", WATER, STATUS, -1, -1, 15 } },
    {"Calm Mind", {"Calm Mind", PSYCHIC, STATUS, -1, -1, 20 } },
    {"Leaf Blade", {"Leaf Blade", GRASS, PHYSICAL, 90, 100, 15 } },
    {"Dragon Dance", {"Dragon Dance", DRAGON, STATUS, -1, -1, 20 } },
    {"Rock Blast", {"Rock Blast", ROCK, PHYSICAL, 25, 90, 10 } },
    {"Shock Wave", {"Shock Wave", ELECTRIC, SPECIAL, 60, -1, 20 } },
    {"Water Pulse", {"Water Pulse", WATER, SPECIAL, 60, 100, 20 } },
    {"Doom Desire", {"Doom Desire", STEEL, SPECIAL, 140, 100, 5 } },
    {"Psycho Boost", {"Psycho Boost", PSYCHIC, SPECIAL, 140, 90, 5 } },
    {"Roost", {"Roost", FLYING, STATUS, -1, -1, 10 } },
    {"Gravity", {"Gravity", PSYCHIC, STATUS, -1, -1, 5 } },
    {"Miracle Eye", {"Miracle Eye", PSYCHIC, STATUS, -1, -1, 40 } },
    {"Wake-Up Slap", {"Wake-Up Slap", FIGHTING, PHYSICAL, 70, 100, 10 } },
    {"Hammer Arm", {"Hammer Arm", FIGHTING, PHYSICAL, 100, 90, 10 } },
    {"Gyro Ball", {"Gyro Ball", STEEL, PHYSICAL, -1, 100, 5 } },
    {"Healing Wish", {"Healing Wish", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Brine", {"Brine", WATER, SPECIAL, 65, 100, 10 } },
    {"Natural Gift", {"Natural Gift", NORMAL, PHYSICAL, -1, 100, 15 } },
    {"Feint", {"Feint", NORMAL, PHYSICAL, 50, 100, 10 } },
    {"Pluck", {"Pluck", FLYING, PHYSICAL, 60, 100, 20 } },
    {"Tailwind", {"Tailwind", FLYING, STATUS, -1, -1, 30 } },
    {"Acupressure", {"Acupressure", NORMAL, STATUS, -1, -1, 30 } },
    {"Metal Burst", {"Metal Burst", STEEL, PHYSICAL, -1, 100, 10 } },
    {"U-turn", {"U-turn", BUG, PHYSICAL, 70, 100, 20 } },
    {"Close Combat", {"Close Combat", FIGHTING, PHYSICAL, 120, 100, 5 } },
    {"Payback", {"Payback", DARK, PHYSICAL, 50, 100, 10 } },
    {"Assurance", {"Assurance", DARK, PHYSICAL, 60, 100, 10 } },
    {"Embargo", {"Embargo", DARK, STATUS, -1, 100, 15 } },
    {"Fling", {"Fling", DARK, PHYSICAL, -1, 100, 10 } },
    {"Psycho Shift", {"Psycho Shift", PSYCHIC, STATUS, -1, 100, 10 } },
    {"Trump Card", {"Trump Card", NORMAL, SPECIAL, -1, -1, 5 } },
    {"Heal Block", {"Heal Block", PSYCHIC, STATUS, -1, 100, 15 } },
    {"Wring Out", {"Wring Out", NORMAL, SPECIAL, -1, 100, 5 } },
    {"Power Trick", {"Power Trick", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Gastro Acid", {"Gastro Acid", POISON, STATUS, -1, 100, 10 } },
    {"Lucky Chant", {"Lucky Chant", NORMAL, STATUS, -1, -1, 30 } },
    {"Me First", {"Me First", NORMAL, STATUS, -1, -1, 20 } },
    {"Copycat", {"Copycat", NORMAL, STATUS, -1, -1, 20 } },
    {"Power Swap", {"Power Swap", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Guard Swap", {"Guard Swap", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Punishment", {"Punishment", DARK, PHYSICAL, -1, 100, 5 } },
    {"Last Resort", {"Last Resort", NORMAL, PHYSICAL, 140, 100, 5 } },
    {"Worry Seed", {"Worry Seed", GRASS, STATUS, -1, 100, 10 } },
    {"Sucker Punch", {"Sucker Punch", DARK, PHYSICAL, 80, 100, 5 } },
    {"Toxic Spikes", {"Toxic Spikes", POISON, STATUS, -1, -1, 20 } },
    {"Heart Swap", {"Heart Swap", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Aqua Ring", {"Aqua Ring", WATER, STATUS, -1, -1, 20 } },
    {"Magnet Rise", {"Magnet Rise", ELECTRIC, STATUS, -1, -1, 10 } },
    {"Flare Blitz", {"Flare Blitz", FIRE, PHYSICAL, 120, 100, 15 } },
    {"Force Palm", {"Force Palm", FIGHTING, PHYSICAL, 60, 100, 10 } },
    {"Aura Sphere", {"Aura Sphere", FIGHTING, SPECIAL, 80, -1, 20 } },
    {"Rock Polish", {"Rock Polish", ROCK, STATUS, -1, -1, 20 } },
    {"Poison Jab", {"Poison Jab", POISON, PHYSICAL, 80, 100, 20 } },
    {"Dark Pulse", {"Dark Pulse", DARK, SPECIAL, 80, 100, 15 } },
    {"Night Slash", {"Night Slash", DARK, PHYSICAL, 70, 100, 15 } },
    {"Aqua Tail", {"Aqua Tail", WATER, PHYSICAL, 90, 90, 10 } },
    {"Seed Bomb", {"Seed Bomb", GRASS, PHYSICAL, 80, 100, 15 } },
    {"Air Slash", {"Air Slash", FLYING, SPECIAL, 75, 95, 15 } },
    {"X-Scissor", {"X-Scissor", BUG, PHYSICAL, 80, 100, 15 } },
    {"Bug Buzz", {"Bug Buzz", BUG, SPECIAL, 90, 100, 10 } },
    {"Dragon Pulse", {"Dragon Pulse", DRAGON, SPECIAL, 85, 100, 10 } },
    {"Dragon Rush", {"Dragon Rush", DRAGON, PHYSICAL, 100, 75, 10 } },
    {"Power Gem", {"Power Gem", ROCK, SPECIAL, 80, 100, 20 } },
    {"Drain Punch", {"Drain Punch", FIGHTING, PHYSICAL, 75, 100, 10 } },
    {"Vacuum Wave", {"Vacuum Wave", FIGHTING, SPECIAL, 40, 100, 30 } },
    {"Focus Blast", {"Focus Blast", FIGHTING, SPECIAL, 120, 70, 5 } },
    {"Energy Ball", {"Energy Ball", GRASS, SPECIAL, 90, 100, 10 } },
    {"Brave Bird", {"Brave Bird", FLYING, PHYSICAL, 120, 100, 15 } },
    {"Earth Power", {"Earth Power", GROUND, SPECIAL, 90, 100, 10 } },
    {"Switcheroo", {"Switcheroo", DARK, STATUS, -1, 100, 10 } },
    {"Giga Impact", {"Giga Impact", NORMAL, PHYSICAL, 150, 90, 5 } },
    {"Nasty Plot", {"Nasty Plot", DARK, STATUS, -1, -1, 20 } },
    {"Bullet Punch", {"Bullet Punch", STEEL, PHYSICAL, 40, 100, 30 } },
    {"Avalanche", {"Avalanche", ICE, PHYSICAL, 60, 100, 10 } },
    {"Ice Shard", {"Ice Shard", ICE, PHYSICAL, 40, 100, 30 } },
    {"Shadow Claw", {"Shadow Claw", GHOST, PHYSICAL, 70, 100, 15 } },
    {"Thunder Fang", {"Thunder Fang", ELECTRIC, PHYSICAL, 65, 95, 15 } },
    {"Ice Fang", {"Ice Fang", ICE, PHYSICAL, 65, 95, 15 } },
    {"Fire Fang", {"Fire Fang", FIRE, PHYSICAL, 65, 95, 15 } },
    {"Shadow Sneak", {"Shadow Sneak", GHOST, PHYSICAL, 40, 100, 30 } },
    {"Mud Bomb", {"Mud Bomb", GROUND, SPECIAL, 65, 85, 10 } },
    {"Psycho Cut", {"Psycho Cut", PSYCHIC, PHYSICAL, 70, 100, 20 } },
    {"Zen Headbutt", {"Zen Headbutt", PSYCHIC, PHYSICAL, 80, 90, 15 } },
    {"Mirror Shot", {"Mirror Shot", STEEL, SPECIAL, 65, 85, 10 } },
    {"Flash Cannon", {"Flash Cannon", STEEL, SPECIAL, 80, 100, 10 } },
    {"Rock Climb", {"Rock Climb", NORMAL, PHYSICAL, 90, 85, 20 } },
    {"Defog", {"Defog", FLYING, STATUS, -1, -1, 15 } },
    {"Trick Room", {"Trick Room", PSYCHIC, STATUS, -1, -1, 5 } },
    {"Draco Meteor", {"Draco Meteor", DRAGON, SPECIAL, 130, 90, 5 } },
    {"Discharge", {"Discharge", ELECTRIC, SPECIAL, 80, 100, 15 } },
    {"Lava Plume", {"Lava Plume", FIRE, SPECIAL, 80, 100, 15 } },
    {"Leaf Storm", {"Leaf Storm", GRASS, SPECIAL, 130, 90, 5 } },
    {"Power Whip", {"Power Whip", GRASS, PHYSICAL, 120, 85, 10 } },
    {"Rock Wrecker", {"Rock Wrecker", ROCK, PHYSICAL, 150, 90, 5 } },
    {"Cross Poison", {"Cross Poison", POISON, PHYSICAL, 70, 100, 20 } },
    {"Gunk Shot", {"Gunk Shot", POISON, PHYSICAL, 120, 80, 5 } },
    {"Iron Head", {"Iron Head", STEEL, PHYSICAL, 80, 100, 15 } },
    {"Magnet Bomb", {"Magnet Bomb", STEEL, PHYSICAL, 60, -1, 20 } },
    {"Stone Edge", {"Stone Edge", ROCK, PHYSICAL, 100, 80, 5 } },
    {"Captivate", {"Captivate", NORMAL, STATUS, -1, 100, 20 } },
    {"Stealth Rock", {"Stealth Rock", ROCK, STATUS, -1, -1, 20 } },
    {"Grass Knot", {"Grass Knot", GRASS, SPECIAL, -1, 100, 20 } },
    {"Chatter", {"Chatter", FLYING, SPECIAL, 60, 100, 20 } },
    {"Judgment", {"Judgment", NORMAL, SPECIAL, 100, 100, 10 } },
    {"Bug Bite", {"Bug Bite", BUG, PHYSICAL, 60, 100, 20 } },
    {"Charge Beam", {"Charge Beam", ELECTRIC, SPECIAL, 50, 90, 10 } },
    {"Wood Hammer", {"Wood Hammer", GRASS, PHYSICAL, 120, 100, 15 } },
    {"Aqua Jet", {"Aqua Jet", WATER, PHYSICAL, 40, 100, 20 } },
    {"Attack Order", {"Attack Order", BUG, PHYSICAL, 90, 100, 15 } },
    {"Defend Order", {"Defend Order", BUG, STATUS, -1, -1, 10 } },
    {"Heal Order", {"Heal Order", BUG, STATUS, -1, -1, 10 } },
    {"Head Smash", {"Head Smash", ROCK, PHYSICAL, 150, 80, 5 } },
    {"Double Hit", {"Double Hit", NORMAL, PHYSICAL, 35, 90, 10 } },
    {"Roar of Time", {"Roar of Time", DRAGON, SPECIAL, 150, 90, 5 } },
    {"Spacial Rend", {"Spacial Rend", DRAGON, SPECIAL, 100, 95, 5 } },
    {"Lunar Dance", {"Lunar Dance", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Crush Grip", {"Crush Grip", NORMAL, PHYSICAL, -1, 100, 5 } },
    {"Magma Storm", {"Magma Storm", FIRE, SPECIAL, 120, 75, 5 } },
    {"Dark Void", {"Dark Void", DARK, STATUS, -1, 80, 10 } },
    {"Seed Flare", {"Seed Flare", GRASS, SPECIAL, 120, 85, 5 } },
    {"Ominous Wind", {"Ominous Wind", GHOST, SPECIAL, 60, 100, 5 } },
    {"Shadow Force", {"Shadow Force", GHOST, PHYSICAL, 120, 100, 5 } },
    {"Hone Claws", {"Hone Claws", DARK, STATUS, -1, -1, 15 } },
    {"Wide Guard", {"Wide Guard", ROCK, STATUS, -1, -1, 10 } },
    {"Guard Split", {"Guard Split", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Power Split", {"Power Split", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Wonder Room", {"Wonder Room", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Psyshock", {"Psyshock", PSYCHIC, SPECIAL, 80, 100, 10 } },
    {"Venoshock", {"Venoshock", POISON, SPECIAL, 65, 100, 10 } },
    {"Autotomize", {"Autotomize", STEEL, STATUS, -1, -1, 15 } },
    {"Rage Powder", {"Rage Powder", BUG, STATUS, -1, -1, 20 } },
    {"Telekinesis", {"Telekinesis", PSYCHIC, STATUS, -1, -1, 15 } },
    {"Magic Room", {"Magic Room", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Smack Down", {"Smack Down", ROCK, PHYSICAL, 50, 100, 15 } },
    {"Storm Throw", {"Storm Throw", FIGHTING, PHYSICAL, 60, 100, 10 } },
    {"Flame Burst", {"Flame Burst", FIRE, SPECIAL, 70, 100, 15 } },
    {"Sludge Wave", {"Sludge Wave", POISON, SPECIAL, 95, 100, 10 } },
    {"Quiver Dance", {"Quiver Dance", BUG, STATUS, -1, -1, 20 } },
    {"Heavy Slam", {"Heavy Slam", STEEL, PHYSICAL, -1, 100, 10 } },
    {"Synchronoise", {"Synchronoise", PSYCHIC, SPECIAL, 120, 100, 15 } },
    {"Electro Ball", {"Electro Ball", ELECTRIC, SPECIAL, -1, 100, 10 } },
    {"Soak", {"Soak", WATER, STATUS, -1, 100, 20 } },
    {"Flame Charge", {"Flame Charge", FIRE, PHYSICAL, 50, 100, 20 } },
    {"Coil", {"Coil", POISON, STATUS, -1, -1, 20 } },
    {"Low Sweep", {"Low Sweep", FIGHTING, PHYSICAL, 65, 100, 20 } },
    {"Acid Spray", {"Acid Spray", POISON, SPECIAL, 40, 100, 20 } },
    {"Foul Play", {"Foul Play", DARK, PHYSICAL, 95, 100, 15 } },
    {"Simple Beam", {"Simple Beam", NORMAL, STATUS, -1, 100, 15 } },
    {"Entrainment", {"Entrainment", NORMAL, STATUS, -1, 100, 15 } },
    {"After You", {"After You", NORMAL, STATUS, -1, -1, 15 } },
    {"Round", {"Round", NORMAL, SPECIAL, 60, 100, 15 } },
    {"Echoed Voice", {"Echoed Voice", NORMAL, SPECIAL, 40, 100, 15 } },
    {"Chip Away", {"Chip Away", NORMAL, PHYSICAL, 70, 100, 20 } },
    {"Clear Smog", {"Clear Smog", POISON, SPECIAL, 50, -1, 15 } },
    {"Stored Power", {"Stored Power", PSYCHIC, SPECIAL, 20, 100, 10 } },
    {"Quick Guard", {"Quick Guard", FIGHTING, STATUS, -1, -1, 15 } },
    {"Ally Switch", {"Ally Switch", PSYCHIC, STATUS, -1, -1, 15 } },
    {"Scald", {"Scald", WATER, SPECIAL, 80, 100, 15 } },
    {"Shell Smash", {"Shell Smash", NORMAL, STATUS, -1, -1, 15 } },
    {"Heal Pulse", {"Heal Pulse", PSYCHIC, STATUS, -1, -1, 10 } },
    {"Hex", {"Hex", GHOST, SPECIAL, 65, 100, 10 } },
    {"Sky Drop", {"Sky Drop", FLYING, PHYSICAL, 60, 100, 10 } },
    {"Shift Gear", {"Shift Gear", STEEL, STATUS, -1, -1, 10 } },
    {"Circle Throw", {"Circle Throw", FIGHTING, PHYSICAL, 60, 90, 10 } },
    {"Incinerate", {"Incinerate", FIRE, SPECIAL, 60, 100, 15 } },
    {"Quash", {"Quash", DARK, STATUS, -1, 100, 15 } },
    {"Acrobatics", {"Acrobatics", FLYING, PHYSICAL, 55, 100, 15 } },
    {"Reflect Type", {"Reflect Type", NORMAL, STATUS, -1, -1, 15 } },
    {"Retaliate", {"Retaliate", NORMAL, PHYSICAL, 70, 100, 5 } },
    {"Final Gambit", {"Final Gambit", FIGHTING, SPECIAL, -1, 100, 5 } },
    {"Bestow", {"Bestow", NORMAL, STATUS, -1, -1, 15 } },
    {"Inferno", {"Inferno", FIRE, SPECIAL, 100, 50, 5 } },
    {"Water Pledge", {"Water Pledge", WATER, SPECIAL, 80, 100, 10 } },
    {"Fire Pledge", {"Fire Pledge", FIRE, SPECIAL, 80, 100, 10 } },
    {"Grass Pledge", {"Grass Pledge", GRASS, SPECIAL, 80, 100, 10 } },
    {"Volt Switch", {"Volt Switch", ELECTRIC, SPECIAL, 70, 100, 20 } },
    {"Struggle Bug", {"Struggle Bug", BUG, SPECIAL, 50, 100, 20 } },
    {"Bulldoze", {"Bulldoze", GROUND, PHYSICAL, 60, 100, 20 } },
    {"Frost Breath", {"Frost Breath", ICE, SPECIAL, 60, 90, 10 } },
    {"Dragon Tail", {"Dragon Tail", DRAGON, PHYSICAL, 60, 90, 10 } },
    {"Work Up", {"Work Up", NORMAL, STATUS, -1, -1, 30 } },
    {"Electroweb", {"Electroweb", ELECTRIC, SPECIAL, 55, 95, 15 } },
    {"Wild Charge", {"Wild Charge", ELECTRIC, PHYSICAL, 90, 100, 15 } },
    {"Drill Run", {"Drill Run", GROUND, PHYSICAL, 80, 95, 10 } },
    {"Dual Chop", {"Dual Chop", DRAGON, PHYSICAL, 40, 90, 15 } },
    {"Heart Stamp", {"Heart Stamp", PSYCHIC, PHYSICAL, 60, 100, 25 } },
    {"Horn Leech", {"Horn Leech", GRASS, PHYSICAL, 75, 100, 10 } },
    {"Sacred Sword", {"Sacred Sword", FIGHTING, PHYSICAL, 90, 100, 20 } },
    {"Razor Shell", {"Razor Shell", WATER, PHYSICAL, 75, 95, 10 } },
    {"Heat Crash", {"Heat Crash", FIRE, PHYSICAL, -1, 100, 10 } },
    {"Leaf Tornado", {"Leaf Tornado", GRASS, SPECIAL, 65, 90, 10 } },
    {"Steamroller", {"Steamroller", BUG, PHYSICAL, 65, 100, 20 } },
    {"Cotton Guard", {"Cotton Guard", GRASS, STATUS, -1, -1, 10 } },
    {"Night Daze", {"Night Daze", DARK, SPECIAL, 85, 95, 10 } },
    {"Psystrike", {"Psystrike", PSYCHIC, SPECIAL, 100, 100, 10 } },
    {"Tail Slap", {"Tail Slap", NORMAL, PHYSICAL, 25, 85, 10 } },
    {"Hurricane", {"Hurricane", FLYING, SPECIAL, 120, 70, 10 } },
    {"Head Charge", {"Head Charge", NORMAL, PHYSICAL, 120, 100, 15 } },
    {"Gear Grind", {"Gear Grind", STEEL, PHYSICAL, 50, 85, 15 } },
    {"Searing Shot", {"Searing Shot", FIRE, SPECIAL, 100, 100, 5 } },
    {"Techno Blast", {"Techno Blast", NORMAL, SPECIAL, 85, 100, 5 } },
    {"Relic Song", {"Relic Song", NORMAL, SPECIAL, 75, 100, 10 } },
    {"Secret Sword", {"Secret Sword", FIGHTING, SPECIAL, 85, 100, 10 } },
    {"Glaciate", {"Glaciate", ICE, SPECIAL, 65, 95, 10 } },
    {"Bolt Strike", {"Bolt Strike", ELECTRIC, PHYSICAL, 130, 85, 5 } },
    {"Blue Flare", {"Blue Flare", FIRE, SPECIAL, 130, 85, 5 } },
    {"Fiery Dance", {"Fiery Dance", FIRE, SPECIAL, 80, 100, 10 } },
    {"Freeze Shock", {"Freeze Shock", ICE, PHYSICAL, 140, 90, 5 } },
    {"Ice Burn", {"Ice Burn", ICE, SPECIAL, 140, 90, 5 } },
    {"Snarl", {"Snarl", DARK, SPECIAL, 55, 95, 15 } },
    {"Icicle Crash", {"Icicle Crash", ICE, PHYSICAL, 85, 90, 10 } },
    {"V-create", {"V-create", FIRE, PHYSICAL, 180, 95, 5 } },
    {"Fusion Flare", {"Fusion Flare", FIRE, SPECIAL, 100, 100, 5 } },
    {"Fusion Bolt", {"Fusion Bolt", ELECTRIC, PHYSICAL, 100, 100, 5 } },
    {"Flying Press", {"Flying Press", FIGHTING, PHYSICAL, 80, 95, 10 } },
    {"Mat Block", {"Mat Block", FIGHTING, STATUS, -1, -1, 15 } },
    {"Belch", {"Belch", POISON, SPECIAL, 120, 90, 10 } },
    {"Rototiller", {"Rototiller", GROUND, STATUS, -1, -1, 10 } },
    {"Sticky Web", {"Sticky Web", BUG, PHYSICAL, -1, -1, 20 } },
    {"Fell Stinger", {"Fell Stinger", BUG, PHYSICAL, 30, 100, 25 } },
    {"Phantom Force", {"Phantom Force", GHOST, PHYSICAL, 90, 100, 10 } },
    {"Trick-or-Treat", {"Trick-or-Treat", GHOST, STATUS, -1, 100, 20 } },
    {"Noble Roar", {"Noble Roar", NORMAL, STATUS, -1, 100, 30 } },
    {"Ion Deluge", {"Ion Deluge", ELECTRIC, STATUS, -1, 25, 25 } },
    {"Parabolic Charge", {"Parabolic Charge", ELECTRIC, SPECIAL, 50, 100, 20 } },
    {"Forest's Curse", {"Forest's Curse", GRASS, STATUS, -1, 100, 20 } },
    {"Petal Blizzard", {"Petal Blizzard", GRASS, PHYSICAL, 90, 100, 15 } },
    {"Freeze-Dry", {"Freeze-Dry", ICE, SPECIAL, 70, 100, 20 } },
    {"Disarming Voice", {"Disarming Voice", FAIRY, SPECIAL, 40, -1, 15 } },
    {"Parting Shot", {"Parting Shot", DARK, STATUS, -1, 100, 20 } },
    {"Topsy-Turvy", {"Topsy-Turvy", DARK, STATUS, -1, 100, 20 } },
    {"Draining Kiss", {"Draining Kiss", FAIRY, SPECIAL, 50, 100, 20 } },
    {"Crafty Shield", {"Crafty Shield", FAIRY, STATUS, -1, -1, 10 } },
    {"Flower Shield", {"Flower Shield", FAIRY, STATUS, -1, -1, 10 } },
    {"Grassy Terrain", {"Grassy Terrain", GRASS, STATUS, -1, -1, 10 } },
    {"Misty Terrain", {"Misty Terrain", FAIRY, STATUS, -1, -1, 10 } },
    {"Electrify", {"Electrify", ELECTRIC, STATUS, -1, -1, 20 } },
    {"Play Rough", {"Play Rough", FAIRY, PHYSICAL, 90, 90, 15 } },
    {"Fairy Wind", {"Fairy Wind", FAIRY, SPECIAL, 40, 100, 30 } },
    {"Moonblast", {"Moonblast", FAIRY, SPECIAL, 95, 100, 15 } },
    {"Boomburst", {"Boomburst", NORMAL, SPECIAL, 140, 100, 10 } },
    {"Fairy Lock", {"Fairy Lock", FAIRY, STATUS, -1, -1, 10 } },
    {"King's Shield", {"King's Shield", STEEL, STATUS, -1, -1, 10 } },
    {"Play Nice", {"Play Nice", NORMAL, STATUS, -1, -1, 20 } },
    {"Confide", {"Confide", NORMAL, STATUS, -1, -1, 20 } },
    {"Water Shuriken", {"Water Shuriken", WATER, PHYSICAL, 15, 100, 20 } },
    {"Mystical Fire", {"Mystical Fire", FIRE, SPECIAL, 65, 100, 10 } },
    {"Spiky Shield", {"Spiky Shield", GRASS, STATUS, -1, -1, 10 } },
    {"Aromatic Mist", {"Aromatic Mist", FAIRY, STATUS, -1, 100, 20 } },
    {"Eerie Impulse", {"Eerie Impulse", ELECTRIC, STATUS, -1, 100, 15 } },
    {"Venom Drench", {"Venom Drench", POISON, PHYSICAL, -1, 100, 20 } },
    {"Powder", {"Powder", BUG, STATUS, -1, 100, 20 } },
    {"Geomancy", {"Geomancy", FAIRY, STATUS, -1, -1, 10 } },
    {"Magnetic Flux", {"Magnetic Flux", ELECTRIC, STATUS, -1, -1, 20 } },
    {"Happy Hour", {"Happy Hour", NORMAL, STATUS, -1, -1, 30 } },
    {"Electric Terrain", {"Electric Terrain", ELECTRIC, STATUS, -1, -1, 10 } },
    {"Dazzling Gleam", {"Dazzling Gleam", FAIRY, SPECIAL, 80, 100, 10 } },
    {"Celebration", {"Celebration", NORMAL, STATUS, -1, -1, 40 } },
    {"Baby-Doll Eyes", {"Baby-Doll Eyes", FAIRY, STATUS, -1, 100, 30 } },
    {"Nuzzle", {"Nuzzle", ELECTRIC, PHYSICAL, 20, 100, 20 } },
    {"Infestation", {"Infestation", BUG, SPECIAL, 20, 100, 35 } },
    {"Power-Up Punch", {"Power-Up Punch", FIGHTING, PHYSICAL, 40, 100, 30 } },
    {"Oblivion Wing", {"Oblivion Wing", FLYING, SPECIAL, 80, 100, 10 } },
    {"Land's Wrath", {"Land's Wrath", GROUND, PHYSICAL, 90, 100, 10 } },
    {"Diamond Storm", {"Diamond Storm", ROCK, PHYSICAL, 100, 95, 5 } },
    {"Hyperspace Hole", {"Hyperspace Hole", PSYCHIC, SPECIAL, 80, -1, 5 } },
    {"Steam Eruption", {"Steam Eruption", WATER, SPECIAL, 110, 95, 5 } },
};